### ISSUE TITLE
Issue 6 for Milestone 3: Training the Model

### ISSUE THREAD

**Issue by NatashaGichira** [NatashaGichira/Challengers-Improving-Delivery-Service-at-Food-Joint-#6]
- [x] Data splitting
- [ ] Bootsrtapping
- [x] Cross validation (basic, repeated or LOOCV)
- [x] Model training for either classification, regression or clustering
- [x] Model performance comparison using resampling (for classification and regression)

**Comment by NatashaGichira** [comment]
Training the model was successful
